# Generated by Django 4.1.5 on 2024-03-09 14:27

import datetime
from django.db import migrations, models
import lendme.models


class Migration(migrations.Migration):

    dependencies = [
        ('lendme', '0007_rename_owner_userprofile_user_alter_blog_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='end_date',
            field=models.DateField(default=lendme.models.default_end_date),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
