# Generated by Django 4.1.5 on 2024-03-09 14:38

import datetime
from django.db import migrations, models
import lendme.models


class Migration(migrations.Migration):

    dependencies = [
        ('lendme', '0008_alter_transaction_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='end_date',
            field=lendme.models.CustomDateField(default=lendme.models.default_end_date),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 3, 9)),
        ),
    ]
